### ISSUE TITLE
New fields

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/alephmarcreader#12]
Priority A (closed by #14):
- ~~024: e-manuscripta (instead of 856)~~
- ~~610 / 710: Körperschaften~~
- ~~300: Physische Beschreibung~~
- ~~500: Anmerkung~~
- ~~520: Inhaltsangabe~~
- ~~041: Sprache standardisiert~~

Priority B:
- 250: Entstehungstufe
- 264: original date (as string)
- 525: Begleitmaterial

Priority C:
- 581: Literatur

**Comment by BalduinLandolt** [comment]
@tobiasschweizer Folgendes meinerseits:
- 500: sollten wir "Allgemeine Anmerkung" nennen
- 525: vielleicht "Anmerkung zu Begleitmaterial"
- 533, 534, 544: Zusammennehmen zu "Anmerkung zu weiteren Fasusngen"

Ausserdem:
- möglicherweise können wir 300, Unterfeld e weglassen.
- 751 (Entstehungsort) hatte ich angegeben, dass das Feld mehrfach vorkommt; das sollte in den Daten bereinigt werden.

Ich halte Dich auf dem Laufenden.
