### ISSUE TITLE
Date: End of time span missing

### ISSUE THREAD

**Issue by BalduinLandolt** [dhlab-basel/alephmarcreader#17]
So far, `get_date()` returns field 046, subfield c, wich can either be  
- single date
- start of time span

Subfield e, which is end of time span is never looked at.

See my excel sheet for more details.  
(There I'm also suggesting to remodel non-standard dates to trivial time spans: E.g. `1739` as `01.01.1739-01.01.1740` etc.)

Generally, if we have time spans, we'd probably also need a method `get_singe_date()`, for example to generate letter titles. Or am I mistaken here?

**Comment by tobiasschweizer** [comment]
I never really looked into this in detail. In order to generate the date in Knora, I use the date given in the title string:

```python
def get_date_from_title(titlestr):
    # year or month precision
    # generally, imprecision is expressed with '00'
    # but there are also cases in which the day is missing (hence optional)
    m = re.match("^(\d{4})-(\d{2})(-(\d{2}))?", titlestr)

    # the expression did not match
    if m is None:
        raise Exception("invalid date: " + titlestr)

    # no date given
    if m.group(0) == "0000-00-00":
        return None

    # check for precision
    # '00' means no day or month given

    # 3 -> day precision (containing '-')
    # 4 -> day precision (without '-')
    if m.group(3) is not None and m.group(4) != '00':
        # a date with day precision
        return "GREGORIAN:" + m.group(1) + '-' + m.group(2) + '-' + m.group(4)
    # 2 -> month precision
    elif m.group(2) is not None and m.group(2) != '00':
        # a date with month precision
        return "GREGORIAN:" + m.group(1) + '-' + m.group(2)
    else:
        # year precision
        return "GREGORIAN:" + m.group(1)

```

**Comment by BalduinLandolt** [comment]
that doesn't work for me, because I work with letters that have no title string...

I suggest using a class `date` that stores the information it gets from BIBB and has methods that return different string interpretations.

Would that make sense?  
In that case, I'd create a branch, where I can give that a shot.  
(Dumb question: Would I branch that from master or from the WIP-branch?)

**Comment by BalduinLandolt** [comment]
Note to self:  
Would be nice to do that propperly.

What I need to produce (reliably) is a date in format `year[-month[-day]][:endYear[-endMonth[-endDay]]`.  
Also, I'd have to decide how I'd produce the xml file names.
