### ISSUE TITLE
get_original_date() is misleading

### ISSUE THREAD

**Issue by BalduinLandolt** [dhlab-basel/alephmarcreader#18]
calling this "original date" (as it is called in BIBB) is somewhat misleading, as it can be place only.

@tobiasschweizer should we rename this?

**Comment by tobiasschweizer** [comment]
Sorry, I am not sure I understand the question.

Are you referring to:

https://github.com/dhlab-basel/alephmarcreader/blob/f09a5caca2f467f6df56831d94d70514586605ab/alephmarcreader/abstractalephmarcreader.py#L401-L419

> calling this "original date" (as it is called in BIBB) is somewhat misleading, as it can be place only.

So there could be a subfield for the place but not the date and then the method name would not make sense?

Which name would you propose?

**Comment by BalduinLandolt** [comment]
> 
> 
> Sorry, I am not sure I understand the question.
> 
> Are you referring to:
> 
> https://github.com/dhlab-basel/alephmarcreader/blob/f09a5caca2f467f6df56831d94d70514586605ab/alephmarcreader/abstractalephmarcreader.py#L401-L419
> 
> > calling this "original date" (as it is called in BIBB) is somewhat misleading, as it can be place only.
> 
> So there could be a subfield for the place but not the date and then the method name would not make sense?
> 
> Which name would you propose?

Exactly.

Maybe very bluntly just call it `get_original_date_and_place()`?

Or a bit more ellegant: `get_letterhead()`, though I'm not sure that's technically correct.

**Comment by tobiasschweizer** [comment]
> Maybe very bluntly just call it get_original_date_and_place()?

That's ok.
