### ISSUE TITLE
Missing Institutions in Author and Recipient

### ISSUE THREAD

**Issue by BalduinLandolt** [dhlab-basel/alephmarcreader#28]
Authors and recipients can be persons _or_ institutions.

our `get_author()` method   
https://github.com/dhlab-basel/alephmarcreader/blob/364839fcabd0210f8265347ecbeee947b0e472c5/alephmarcreader/abstractalephmarcreader.py#L254-L271  
(and `get_recipient()` respectively)  
only check persons.

So basically, wherever we look for functions in field 600 or 700, we also need to look in 610 and 710.

This should be a fairly easy fix, and won't require any changes to the API or anything. So that could become the hotfix v1.0.1...

@tobiasschweizer Shall I take care of it?

**Comment by tobiasschweizer** [comment]
Persons and institutions are different entities, so I would suggest to create a class `Institution`.

`get_author` could then return persons and institutions, but the client would know about this by looking at the class.

**Comment by BalduinLandolt** [comment]
https://github.com/dhlab-basel/alephmarcreader/blob/364839fcabd0210f8265347ecbeee947b0e472c5/alephmarcreader/abstractalephmarcreader.py#L26-L41

we do have a class `Organisation` which is synonymous to `Institution`, I guess.

So basically, `get_author` would return `[Person|Organisation]`, right?

**Comment by tobiasschweizer** [comment]
yes, I guess

**Comment by BalduinLandolt** [comment]
Is it a too "Java way of thinking" if I suggest the following solution?

Let's have an abstract class `AbstractCorrespondent`, and have both `Person` and `Organisation` be a subclass of that.  
Not only would that "centralise" the features that Person and Organisation have in common (like GND, name, role), but then `get_author()` and `get_recipient()` could just return an object `AbstractCorrespondent`, which would be correct in any case.

What do you think?

**Comment by tobiasschweizer** [comment]
Yes, I think this is a good idea. You could call it even `Correspondent`, possibly declare it as an abstract class so it could not be instantiated directly, just its subclasses. 

Could there be a string member that would directly indicate the type of the subclass, i.e. "person" or "organisation"? So when using `get_author()` or `get_recipient()` it would be easy to decide whether it is a person or an institution, without having to rely on `type()` or `isinstance()`?
